# Generated by Django 4.0.6 on 2022-07-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize_bond_draw_manager', '0002_alter_prizebonddraw_draw_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizebonddraw',
            name='draw_term',
            field=models.IntegerField(unique=True),
        ),
    ]
